### ISSUE TITLE
WorldGeneratorAPI error

### ISSUE THREAD

**Issue by mystical1** [BentoBoxWorld/Boxed#11]
#### 
21:24:47] [Server thread/ERROR]: [BentoBox] [Boxed] WorldGeneratorAPI plugin is required.
[21:24:47] [Server thread/ERROR]: [BentoBox] [Boxed] Download the correct one for your server 

#### Steps to reproduce the behavior
I have got the correct versions for all the plugins and server, I have even discussed in the discord server and was told  they didnt know why it didnt work 

#### Expected behavior
Usually Bentobox plugins work 

##### Output of `/bbox version` (Mandatory)

```
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
Can you do /plugins and share the result? What is the file you installed for WorldGeneratorAPI and where did you get it?

**Comment by tastybento** [comment]
I just read the discord and it looks like it is installed. So, could you start you server and then share your complete start up console log? Then I can try and see what might be happening. Just zip it up and drag and drop here.

**Comment by tastybento** [comment]
This issue was caused by a case-sensitive check issue on Windows OS.
