### ISSUE TITLE
Nether borders

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Boxed#16]
#### Is your feature request related to a problem?
In my opinion, nether boundaries should be 8 times smaller than the boundaries opened in the world.

Because opened portals can cause problems and I don't think it is right for us to give players as much space as we do in the normal world.

**Comment by tastybento** [comment]
Players should only have access to blocks within their box. Also, the overworld and nether world dimensions are mapped 1:1 in Boxed, so there's no magnification of travel between them (there shouldn't be).

>Because opened portals can cause problems and I don't think it is right for us to give players as much space as we do in the normal world.

I don't understand. What problems does it generate?

**Comment by OverBrave** [comment]
Okay then, it looks like it's okay. Thanks.
