### ISSUE TITLE
Placeholder: Boxed Island's Advancements

### ISSUE THREAD

**Issue by Fredthedoggy** [BentoBoxWorld/Boxed#20]
**Description**

A Placeholder to show how many advancements have been given to a box.
Should not include Advancements that grant `0` upgrade, but negatives should still be counted.

**Placeholder**: `%boxed_island_advancements%`

**Comment by tastybento** [comment]
Add two placeholders that list the number of advancements done for a box

`%boxed_island_advancements%` - the number of advancements for a particular user
`%boxed_visited_island_advancements%` - the number of advancements based on where the user is located.

If there is no box, the return value is "". Values are still given if the player is outside the protected area but inside the overall potential box size.

Only advancements that were not automatically given are counted.
