### ISSUE TITLE
Nether related

### ISSUE THREAD

**Issue by SeptyIsHere** [BentoBoxWorld/Boxed#27]
#### Describe the bug

Hello, we have 2 bugs, they're not very big and they don't make the game unplayable, but I have 12-14 year olds kids in my server, and they're very confused so the first bug is:
https://imgur.com/a/aUFdqDM - Nether multiplication bug
https://imgur.com/a/ttynFgw - Spawn outside of the border
#### Steps to reproduce the behavior

For the first bug:
1) Build a nether portal
2) Travel with it
3) Go back in the portal
4) Do this like 2-3 times and you should notice!
For the second bug
1) Build a nether portal
2) Travel with it
3) If the nether portal didn't spawn outside of the border, do that again. (In nether)

#### Expected behavior

For the first bug, the nether portal to not "respawn" 1 million times
For the second bug, the nether portal to spawn in the middle of the nether border?

#### Screenshots and videos (Optional)

In the first step

##### Output of `/bbox version` (Mandatory)

```
[08:20:04 INFO]: Running Invalid (TUINITY) 1.16.5.
[08:20:04 INFO]: BentoBox version: 1.16.2-SNAPSHOT-b2040
[08:20:04 INFO]: Database: JSON
[08:20:04 INFO]: Loaded Game Worlds:
[08:20:04 INFO]: boxed_world (Boxed): Overworld, Nether, The End*
[08:20:04 INFO]: Loaded Addons:
[08:20:04 INFO]: Border 3.1.1 (ENABLED)
[08:20:04 INFO]: Boxed 1.1.5 (ENABLED)
[08:20:04 INFO]: TwerkingForTrees 1.4.1 (ENABLED)

```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
To fix the multiple portal bug use the latest snapshot release of BentoBox. Download from ci.BentoBox.world. 

The latest version of Border has a system that will drag a player back inside the border if they end up in a portal outside.  Sometimes the portal is placed outside because of the server's safety check.

**Comment by SeptyIsHere** [comment]
Alright, I'll try this today, if I don't come back, you're more than welcome to close my issue.

**Comment by tastybento** [comment]
I'll close. If you need more help, let me know.
