### ISSUE TITLE
Boxed not working while executing /box

### ISSUE THREAD

**Issue by jordyrb** [BentoBoxWorld/Boxed#35]
### Expected behavior

create an box when using the command /box

### Observed/Actual behavior

gives me an error --> https://pastebin.com/0j9wTSG2

### Steps/models to reproduce

https://pastebin.com/0j9wTSG2

### BentoBox version

BentoBox-1.17.3

### Plugin list

AdvancedBan, AdvancedChests, AdvancedNMotd, BentoBox, CustomTab*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, PlaceholderAPI, PlayerVaults, PlugMan, ProtocolLib, ShopGUIPlus, Vault, VoidWorld*, WildStacker, WorldBorderAPI, WorldGeneratorApi, WorldGuard

### Other

first time it working then i deleted the box with /boxadmin delete "name"
since then i can't create another box

**Comment by jordyrb** [comment]
first time i created an box it did work and yes i am using latest worldgeneratorAPI but imma try paperspigot now first

**Comment by jordyrb** [comment]
https://pastebin.com/c7Pc6qUg
full latest log with paper bentobox isn't even loading in

**Comment by tastybento** [comment]
There is a bad island file in the database. It's in BentoBox/database/Island and it will have this as part of its filename: e050d1fb-6813-4d2a-9464-fe5ebf5c0997

Find the file, download it and share it here, but you need to delete it. Then try to restart.

**Comment by jordyrb** [comment]
ow sorry i deleted it to quickly didnt saw you needed it but thanks its fixed

**Comment by tastybento** [comment]
ok!
