### ISSUE TITLE
Boxed: Disable structure and stronghold generation

### ISSUE THREAD

**Issue by DeltaX86** [BentoBoxWorld/Boxed#39]
### Expected behavior

The world should be created without structures and strongholds.

### Observed/Actual behavior

The world that is generated has structures and stronghold.

### Steps/models to reproduce

Addon boxed/config.yml
world:
  friendly-name: Boxed
  world-name: boxed_world
  seed: 978573758696
  difficulty: NORMAL
  allow-structures: false
  allow-strongholds: false

### BentoBox version

Java 16
Paper 1.17.1 
Version de BentoBox : 1.18.1
Base de données : JSON
Mondes de jeu chargés :
boxed_world (Boxed) : Overworld, Nether
Addons chargés :
Bank 1.4.0-SNAPSHOT-b58 (ENABLED)
Border 3.3.0-SNAPSHOT-b136 (ENABLED)
Boxed 1.2.2-SNAPSHOT-b114 (ENABLED)
Chat 1.1.4 (ENABLED)
Greenhouses 1.7.0-SNAPSHOT-b317 (ENABLED)
Level 2.9.0-SNAPSHOT-b494 (ENABLED)
Limits 1.19.0 (ENABLED)
Warps 1.11.2-SNAPSHOT-b319 (ENABLED)

### Plugin list

WorldGeneratorApi-1.2.2-bukkit.jar
worldborderapiplugin-1.171.0-all.jar

### Other

bukkit.yml:
worlds:
  boxed_world:
    generator: WorldBorderApi

server.properties:
enerate-structures=false

**Comment by tastybento** [comment]
Boxed isn't really compatible with 1.18.1 yet. I'm the process of rewriting it. You could try the latest version of WorldGeneratorApi and see if that helps: https://github.com/rutgerkok/WorldGeneratorApi/releases/tag/v1.3

**Comment by DeltaX86** [comment]
Hello, server is in 1.17.1 not in 1.18.1.
Version of bentobox is 1.18.1
Thx

**Comment by DeltaX86** [comment]
Hello,  IN JAVA 16 and PAPER 1.17.1
I have test WorldGeneratorApi v1.3 : 
 BentoBox v1.18.1 , which was built for WorldGeneratorApi v0.5, will not be compatible with WorldGeneratorApi v2.0. Please look for an update of BentoBox
 I need world with no structures, natural spawners, stronghold, etc ....
 Please help

**Comment by DeltaX86** [comment]
> Boxed isn't really compatible with 1.18.1 yet. I'm the process of rewriting it. You could try the latest version of WorldGeneratorApi and see if that helps: https://github.com/rutgerkok/WorldGeneratorApi/releases/tag/v1.3

**Comment by tastybento** [comment]
Not applicable anymore. Game has been rewritten.
