### ISSUE TITLE
New version support

### ISSUE THREAD

**Issue by luobochuanqi** [BentoBoxWorld/Boxed#40]
### Is your feature request related to a problem?

Many plugins have been updated to 1.18 and are not compatible with this project

### Describe the solution you'd like.

Update to support 1.18.2,thanks

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
BentoBox supports 1.18.2.

The message in 1.20 release version is there because 1.20 was released before 1.18.2 came out.

There is a dev version that has fixed the warning message, but because there is no actual issues with the compatibility, the release is not pushed.

**Comment by OverBrave** [comment]
@tastybento What is the future of this game mode? Will it continue to be developed? No updates for a long time.

I hope this game mode continues to be developed, I think it is a very original and nice game mode.

**Comment by tastybento** [comment]
I am glad to say that I have a prototype working using the new spigot custom world generation API. It's going to be a bit different to the previous versions but it should be good. It's in progress now.
