### ISSUE TITLE
Pre-Generate Boxes

### ISSUE THREAD

**Issue by Fredthedoggy** [BentoBoxWorld/Boxed#5]
#### Is your feature request related to a problem?

My server (like most others) takes a while to generate a box, as its pasting `2,000` blocks.

#### Describe the solution you'd like us to implement.

The Solution I suggest is pre-generating 2-3 (Customizable in the config) Boxes, at a much slower speed to not affect the TPS.
This way if 2 people join at the same time, it doesn't take 5 minutes for one to play.

#### Describe alternatives you've considered.

N/A

### Additional context

N/A

**Comment by tastybento** [comment]
What is actually taking the time is the world generation around those blocks (2000 will paste in < 1 second). But I get the request. It's a good request.

**Comment by tastybento** [comment]
This is in progress: https://github.com/BentoBoxWorld/BentoBox/pull/1734

**Comment by tastybento** [comment]
Closing old issues.
