### ISSUE TITLE
the enderpearls move the box

### ISSUE THREAD

**Issue by haroldrc** [BentoBoxWorld/Boxed#50]
### Expected behavior

ALLOW_MOVE_BOX: false

but the box keeps moving

### Observed/Actual behavior

ALLOW_MOVE_BOX: false

but the box keeps moving

### Steps/models to reproduce

ALLOW_MOVE_BOX: false

but the box keeps moving

### BentoBox version

1.23.2

**Comment by tastybento** [comment]
Should be fixed. Try the version on ci.bentobox.world when it finishes building.

**Comment by haroldrc** [comment]
the bug has been fixed, but now it is impossible to leave the box in any way (/spawn etc)

![image](https://github.com/BentoBoxWorld/Boxed/assets/29206120/fb87f619-e162-4f26-a3b8-8a68369cf615)

**Comment by tastybento** [comment]
Okay, done. Please confirm.
