### ISSUE TITLE
range not saved

### ISSUE THREAD

**Issue by haroldrc** [BentoBoxWorld/Boxed#59]
### Expected behavior

that the changes are saved

### Observed/Actual behavior

the range changed with this "boxed range set" command is not saved

(i disabled the advancement https://pastebin.com/xRZMutjb)

### Steps/models to reproduce

- boxed range set _number_
- left the game
- join the game

### BentoBox version

[15:35:42 INFO]: Notmicix06 nuovo bilancio: 37,256.00:astra:
[15:35:42 INFO]: Impostato il raggio di protezione a 2.
[15:37:52 INFO]: In esecuzione su Invalido (PUFFERFISH) 1.20.1.
[15:37:52 INFO]: Versione BentoBox: 1.24.1-SNAPSHOT-b2435
[15:37:52 INFO]: Database: MYSQL
[15:37:52 INFO]: Mondi di gioco caricati:
[15:37:52 INFO]: contea (Contea): Overworld, Nether, End
[15:37:52 INFO]: Addons caricati:
[15:37:52 INFO]: Border 4.1.1-SNAPSHOT-b182 (ENABLED)
[15:37:52 INFO]: Boxed 2.3.1-SNAPSHOT-b241 (ENABLED)
[15:37:52 INFO]: InvSwitcher 1.12.0-SNAPSHOT-b226 (ENABLED)
[15:37:52 INFO]: Level 2.11.0-SNAPSHOT-b540 (ENABLED)

**Comment by alessiaciotta** [comment]
i have the same problem

**Comment by tastybento** [comment]
Yes, this is because the box size is recalculated based on the advancements that the player has done. That gets triggered when they teleport to the box or login or complete an advancement. So, yes, this is only a temporary setting. 
What is it that you are trying to do by setting the box size? I can look to see if there's a way to handle this but the issue is that box sizes can always go up. Are you trying to give the player a "boost"?

**Comment by alessiaciotta** [comment]
i want the border size to go up only by commands. and i want the achievements to be disabled. @tastybento

**Comment by tastybento** [comment]
Okay. Noted. I'll see what can be done for that.

**Comment by alessiaciotta** [comment]
not to press you but how long would it take? @tastybento

**Comment by tastybento** [comment]
This is quite a big change. At least a week. As a work around, if you give the root advancement some value then everyone could get the same size.

**Comment by tastybento** [comment]
I found a simple way to do it. I added a config option in AOneBlock's config.yml:

```
# Ignore advancements
  # If this is true, advancements will not change the size of the box.
  ignore-advancements: false
```

Set it to true and the box size will not be affected by advancements. You can try the latest build from ci.bentobox.world to try it out. Take backups just in case, but it should be safe. It just turns off all the advancement checking and setting the box size.

**Comment by Reyretee** [comment]
> I found a simple way to do it. I added a config option in AOneBlock's config.yml:
> 
> ```
> # Ignore advancements
>   # If this is true, advancements will not change the size of the box.
>   ignore-advancements: false
> ```
> 
> Set it to true and the box size will not be affected by advancements. You can try the latest build from ci.bentobox.world to try it out. Take backups just in case, but it should be safe. It just turns off all the advancement checking and setting the box size.




Isn't this issue for the plugin's boxed mode? You said you fixed it for AOneBlock mode.

I couldn't find such a setting in the Boxed plugin settings.

"/boxadmin range set <player> <amount> or /boxadmin range add <player> <amount>" commands do not work properly.

**Comment by tastybento** [comment]
Sorry, I meant Boxed. 
I have not done a release yet of Boxed so you would need to download the latest version from the CI. Ci.Bentobox.world

**Comment by Reyretee** [comment]
> Sorry, I meant Boxed. I have not done a release yet of Boxed so you would need to download the latest version from the CI. Ci.Bentobox.world

I was trying the version you said and I found a little bug. I hope this helps you.

Ender Pearl glitch
https://www.youtube.com/watch?v=1FTTwqBLS_A

**Comment by BONNe** [comment]
> > Sorry, I meant Boxed. I have not done a release yet of Boxed so you would need to download the latest version from the CI. Ci.Bentobox.world
> 
> I was trying the version you said and I found a little bug. I hope this helps you.
> 
> ignore-advancements: true "/boxadmin range add and /boxadmin range set " works fine.
> 
> Ender Pearl glitch https://www.youtube.com/watch?v=1FTTwqBLS_A

What exactly is glitching? The size of the box or?
I do not understand from video. Could you explain it more?

**Comment by Reyretee** [comment]
> > > Sorry, I meant Boxed. I have not done a release yet of Boxed so you would need to download the latest version from the CI. Ci.Bentobox.world
> > 
> > 
> > I was trying the version you said and I found a little bug. I hope this helps you.
> > ignore-advancements: true "/boxadmin range add and /boxadmin range set " works fine.
> > Ender Pearl glitch https://www.youtube.com/watch?v=1FTTwqBLS_A
> 
> What exactly is glitching? The size of the box or? I do not understand from video. Could you explain it more?


When using the Ender pearl it will normally send you to your registered home instead of sending you off the map, so you can't go outside the map and the specified border. But when I try this in the unreleased plugin version and use the ender pearl, it sends me out of bounds and my terrain changes completely. So I can exceed the border and continue the game in a new location, and when I type "/box" again, it continues to send me to the new location.

**Comment by BONNe** [comment]
That is a feature of Boxed addon. 
Players can move their Box with ender pearls.

If you do not want players to have such ability, you can disable it by toggling `ALLOW_MOVE_BOX` flag in world settings.

**Comment by Reyretee** [comment]
> That is a feature of Boxed addon. Players can move their Box with ender pearls.
> 
> If you do not want players to have such ability, you can disable it by toggling `ALLOW_MOVE_BOX` flag in world settings.

Sorry, then this is entirely my fault. Sorry for making a wrong comment.
