### ISSUE TITLE
Enable plugin to scale across multiple worlds or servers

### ISSUE THREAD

**Issue by matteobaldassarre** [BentoBoxWorld/Boxed#60]
I would like Boxed to be able to scale across multiple worlds and servers (bungeecord).

Currently you can set a max number of players area for the world_boxed but of course this is not a scalable solution if the plugin doesn't create another world when the max players area count is reached.

It would also be cool if the plugin could be able to scale across multiple servers like in bungeecord system.
Like if I'm in server1 and my friend wants to co-op in my box that is in server2, I should be able to invite him cross-server.

**Comment by BONNe** [comment]
Boxes it self is just world generation. Addon for BentoBox.
Any load balancing would be happening in BentoBox and not in Boxed.

And there is already a feature request for that: https://github.com/BentoBoxWorld/BentoBox/issues/157
