### ISSUE TITLE
Visitors cannot TP to another box if they're standing in their own box/

### ISSUE THREAD

**Issue by Projecki** [BentoBoxWorld/Boxed#70]
### Expected behavior

Users can tp to you from their box to your box

### Observed/Actual behavior

Players receive a "You cannot teleport outside of your box" error when they try to TP to you

### Steps/models to reproduce

1. Be in boxed world
2. TP to friend in their box in boxed world
3. Get error

### BentoBox version

[16:38:16 INFO]: Running Invalid (AXOLOTL) 1.20.4.
[16:38:16 INFO]: (git-Axolotl-"fbb016d" (MC: 1.20.4))
[16:38:16 INFO]: BentoBox version: 2.3.0
[16:38:16 INFO]: Database: MARIADB
[16:38:16 INFO]: Loaded Game Worlds:
[16:38:16 INFO]: boxed_world (Boxed): Overworld, Nether
[16:38:16 INFO]: Loaded Addons:
[16:38:16 INFO]: Border 4.3.0 (ENABLED)
[16:38:16 INFO]: Boxed 2.5.0 (ENABLED)

### Other

I see now that if you TP from a non-boxed world, it will allow you in.

This is a lil janky tho. Why can't users TP from their box to your box?

**Comment by tastybento** [comment]
This is a general anti-tp protection to prevent folks from somehow escaping their box by teleporting. I will have to think about if I can allow the type of TPing you mention or if I should remove this protection and just let Border handle it.

**Comment by Projecki** [comment]
Perhaps a config toggle?

It would be greatly appreciated. I'd love for players to be able to visit other boxes easily. Player warps & chest shop style economy for my server!

**Comment by tastybento** [comment]
The latest build should allow this. Please try it.
