### ISSUE TITLE
/boxadmin resets command issues

### ISSUE THREAD

**Issue by Projecki** [BentoBoxWorld/Boxed#71]
### Expected behavior

/boxadmin resets <add/remove/reset/set> <username> <amount>

This command is not working. Despite receiving a confirmation message that my reset total has been increased, I am unable to reset my box again.

### Observed/Actual behavior

![image](https://github.com/BentoBoxWorld/Boxed/assets/65093423/66f44e0e-cdd8-425b-99cd-01189cac1348)
https://docs.bentobox.world/en/latest/gamemodes/Boxed/Commands/

See here, I increase my resets, and set my resets, but in reality I am unable to use the additional resets

Additionally, in documentation, the command is listed as "/boxadmin reset" when in reality the only working command is "/boxadmin resets", resets is plural. Also the documentation lacks a description for this command, in its place is the text "
commands.admin.resets.reset.description"

Same goes for the default config comments, where the incorrect command "/boxadmin reset" is referenced.

### Steps/models to reproduce

use /boxadmin resets command

### BentoBox version

[20:09:09 INFO]: Running Invalid (AXOLOTL) 1.20.4.
[20:09:09 INFO]: (git-Axolotl-"fbb016d" (MC: 1.20.4))
[20:09:09 INFO]: BentoBox version: 2.3.0
[20:09:09 INFO]: Database: MARIADB
[20:09:09 INFO]: Loaded Game Worlds:
[20:09:09 INFO]: boxed_world (Boxed): Overworld, Nether
[20:09:09 INFO]: Loaded Addons:
[20:09:09 INFO]: Border 4.3.0 (ENABLED)
[20:09:09 INFO]: Boxed 2.5.0 (ENABLED)

**Comment by tastybento** [comment]
This command is confusing. The command sets how many times you have reset the island. If you want to allow you to reset again then set it to 0.

**Comment by tastybento** [comment]
No problem.
