### ISSUE TITLE
Sync Teammate Advancements

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/Boxed#8]
#### Is your feature request related to a problem?

When player's start a team box, and one person gets an advancement it does not show up in the other player's advancement menus.

#### Describe the solution you'd like us to implement.

Add a (configurable) option to grant players all advancements that their teammates have unlocked, while they are offline / when they are both online, grant the advancement to all team members.

#### Describe alternatives you've considered.

A custom plugin to do this (not really an alternative)

### Additional context

N/A

**Comment by tastybento** [comment]
Requires the latest SNAPSHOT BentoBox.
