### ISSUE TITLE
Jigsaw Block Not Working

### ISSUE THREAD

**Issue by qarbon1** [BentoBoxWorld/Boxed#82]
### Expected behavior

For the jigsaw to work

### Observed/Actual behavior

![image_2024-07-22_012259532](https://github.com/user-attachments/assets/688f1fa7-ea53-4018-975e-901512872652)

### Steps/models to reproduce

I don't know, I just started everything up

### BentoBox version

2.4.1

**Comment by tastybento** [comment]
What version of Minecraft are you running on?

**Comment by qarbon1** [comment]
1.20.6

**Comment by tastybento** [comment]
Should work in https://github.com/BentoBoxWorld/Boxed/releases/tag/2.6.0
