### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by qarbon1** [BentoBoxWorld/Boxed#84]
### Expected behavior

Nothing

### Observed/Actual behavior

Nothing

### Steps/models to reproduce

Nothing

### BentoBox version

2.4.1

### Other

Is there any way for me to use a multi-world plugin with boxed?

**Comment by tastybento** [comment]
I think https://www.spigotmc.org/resources/multiworld-bukkit.92559/ works. But I cannot say for sure.

**Comment by qarbon1** [comment]
Hi! May I please have a private discussion with ya?
